name = "PlotGraphviz"
uuid = "78a92bc3-407c-4e2f-aae5-75bb47a6fe36"
authors = ["tragisch <uwe@roettgermann.de> and contributors"]
version = "0.6.2"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
ShowGraphviz = "14e20f5a-e304-4f94-b7d9-bca841234ddf"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[compat]
Graphs = "1"
ParserCombinator = "2"
ShowGraphviz = "0.1"
SimpleWeightedGraphs = "1"
julia = "1" 

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
